modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "halflifemenu"
version = "${version}"
displayName = "Half-Life Menu"
authors = "WindClan"
description = '''
This mod makes some Minecraft menus look like they are from Half Life (v1.1.1.1)
'''
logoFile = "assets/halflifemenu/icon.png"


[[dependencies.halflifemenu]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "halflifemenu.mixins.json"